### PR TITLE
RFC: Type Metamethod Support

### PR DESCRIPTION
**Pull request by metatablecat**
Suggests allowing developers to use the __type metamethod mechanism.

[Rendered Link](https://github.com/metatablecat/rfcs/blob/type-metamethod/docs/type-metamethod-support.md)

### CODE REVIEW

**Comment by vegorov-rbx** [comment]
We specifically excluded support for __type override for the reasons mentioned in the drawbacks.
As such, we do not plan to accept this RFC.

**Comment by alexmccord** [comment]
This also breaks type refinements as a feature.

**Comment by vegorov-rbx** [comment]
It also break type guards in native codegen.
Injecting a prefix dynamically kills typeof performance and guaranteeing statically that type will have prefix and will not change is impossible because metatables are mutable.

**Comment by alexmccord** [comment]
Yeah. The feature already exists in the form of tagged unions, use them.

**Pull request closed without merging**
